lenguage: node_js
node_js:
  - 7
install:
  - npm install
script:
  - npm run test       
  - echo funcionaaaaa
deploy:
  provider: heroku
  api_key:
    secure: b7e75911-b530-44b9-b7d6-901d33e0c1cc
  app: travisprueba
after_deploy:
  - cat package.json
 